version: '3.8'
services:
  flask-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./downloads:/app/downloads
      - ./reports:/app/reports
      - ./quarantine:/app/quarantine
